//go:build ignore

package main

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
)

const (
	eastAsianWidthURL = "https://unicode.org/Public/UNIDATA/EastAsianWidth.txt"
	emojiDataURL      = "https://unicode.org/Public/UNIDATA/emoji/emoji-data.txt"
	outputFile        = "unicode_data.go"
	outputPackage     = "diferenco"
)

type interval struct {
	first rune
	last  rune
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "gen_unicode: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	cjkRanges, err := fetchRanges(eastAsianWidthURL, func(prop string) bool {
		return prop == "W" || prop == "F"
	})
	if err != nil {
		return fmt.Errorf("load EastAsianWidth data: %w", err)
	}

	emojiRanges, err := fetchRanges(emojiDataURL, func(prop string) bool {
		return prop == "Extended_Pictographic" || prop == "Emoji" || prop == "Emoji_Component"
	})
	if err != nil {
		return fmt.Errorf("load emoji data: %w", err)
	}

	var buf bytes.Buffer
	writeHeader(&buf)
	writeIntervals(&buf, "cjkRanges", cjkRanges)
	writeIntervals(&buf, "emojiRanges", emojiRanges)

	if err := writeFileAtomically(outputFile, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outputFile, err)
	}
	return nil
}

func fetchRanges(url string, wantProperty func(string) bool) ([]interval, error) {
	resp, err := http.Get(url)
	if err != nil {
		return nil, fmt.Errorf("GET %s: %w", url, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 4<<10))
		return nil, fmt.Errorf("GET %s: status %s: %s", url, resp.Status, strings.TrimSpace(string(body)))
	}

	var ranges []interval
	scanner := bufio.NewScanner(resp.Body)

	for lineNo := 1; scanner.Scan(); lineNo++ {
		line := stripComment(scanner.Text())
		if line == "" {
			continue
		}

		codePointPart, propertyPart, ok := strings.Cut(line, ";")
		if !ok {
			continue
		}

		property := strings.TrimSpace(propertyPart)
		if !wantProperty(property) {
			continue
		}

		r, err := parseInterval(strings.TrimSpace(codePointPart))
		if err != nil {
			return nil, fmt.Errorf("%s:%d: %w", url, lineNo, err)
		}
		ranges = append(ranges, r)
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan %s: %w", url, err)
	}

	return mergeIntervals(ranges), nil
}

func stripComment(s string) string {
	s, _, _ = strings.Cut(s, "#")
	return strings.TrimSpace(s)
}

func parseInterval(s string) (interval, error) {
	if start, end, ok := strings.Cut(s, ".."); ok {
		first, err := parseHexRune(start)
		if err != nil {
			return interval{}, fmt.Errorf("invalid range start %q: %w", start, err)
		}
		last, err := parseHexRune(end)
		if err != nil {
			return interval{}, fmt.Errorf("invalid range end %q: %w", end, err)
		}
		if first > last {
			return interval{}, fmt.Errorf("invalid range %q: start > end", s)
		}
		return interval{first: first, last: last}, nil
	}

	r, err := parseHexRune(s)
	if err != nil {
		return interval{}, fmt.Errorf("invalid code point %q: %w", s, err)
	}
	return interval{first: r, last: r}, nil
}

func parseHexRune(s string) (rune, error) {
	v, err := strconv.ParseUint(strings.TrimSpace(s), 16, 32)
	if err != nil {
		return 0, err
	}
	return rune(v), nil
}

func mergeIntervals(ranges []interval) []interval {
	if len(ranges) == 0 {
		return nil
	}

	sort.Slice(ranges, func(i, j int) bool {
		if ranges[i].first != ranges[j].first {
			return ranges[i].first < ranges[j].first
		}
		return ranges[i].last < ranges[j].last
	})

	out := make([]interval, 0, len(ranges))
	out = append(out, ranges[0])

	for _, r := range ranges[1:] {
		last := &out[len(out)-1]

		if r.first <= last.last+1 {
			if r.last > last.last {
				last.last = r.last
			}
			continue
		}

		out = append(out, r)
	}

	return out
}

func writeHeader(w io.Writer) {
	fmt.Fprintln(w, "// Code generated by gen_unicode.go. DO NOT EDIT.")
	fmt.Fprintln(w)
	fmt.Fprintf(w, "package %s\n\n", outputPackage)
}

func writeIntervals(w io.Writer, name string, ranges []interval) {
	fmt.Fprintf(w, "var %s = []interval{\n", name)
	for _, r := range ranges {
		fmt.Fprintf(w, "\t{0x%04X, 0x%04X},\n", r.first, r.last)
	}
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w)
}

func writeFileAtomically(name string, data []byte, perm os.FileMode) error {
	tmp := name + ".tmp"

	if err := os.WriteFile(tmp, data, perm); err != nil {
		return err
	}
	if err := os.Rename(tmp, name); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}
