// Package diferenco provides diff and merge functionality.
//
// This file (merge_new_test.go) contains comprehensive tests for MergeParallel and HasConflictParallel.
// These tests were generated by GLM-5 (Zhipu AI) to validate the three-way merge implementation.
package diferenco

import (
	"context"
	"strings"
	"testing"
	"unicode/utf8"
)

// ============================================================================
// Basic Tests
// ============================================================================

// TestMergeParallelBasic tests basic merge scenarios
func TestMergeParallelBasic(t *testing.T) {
	tests := []struct {
		name         string
		origin       string
		ours         string
		theirs       string
		style        int
		wantConflict bool
	}{
		{
			name:         "conflict_default",
			origin:       "line1\nline2\n",
			ours:         "line1a\nline2\n",
			theirs:       "line1b\nline2\n",
			style:        STYLE_DEFAULT,
			wantConflict: true,
		},
		{
			name:         "conflict_diff3",
			origin:       "line1\nline2\n",
			ours:         "line1a\nline2\n",
			theirs:       "line1b\nline2\n",
			style:        STYLE_DIFF3,
			wantConflict: true,
		},
		{
			name:         "no_conflict_adjacent",
			origin:       "line1\nline2\n",
			ours:         "line1a\nline2\n",
			theirs:       "line1\nline2a\n",
			style:        STYLE_DEFAULT,
			wantConflict: false, // Adjacent (non-overlapping) changes should NOT conflict
		},
		{
			name:         "empty_texts",
			origin:       "",
			ours:         "",
			theirs:       "",
			style:        STYLE_DEFAULT,
			wantConflict: false,
		},
		{
			name:         "ours_empty",
			origin:       "line1\nline2\n",
			ours:         "",
			theirs:       "line1\nline2\n",
			style:        STYLE_DEFAULT,
			wantConflict: false,
		},
		{
			name:         "theirs_empty",
			origin:       "line1\nline2\n",
			ours:         "line1\nline2\n",
			theirs:       "",
			style:        STYLE_DEFAULT,
			wantConflict: false,
		},
		{
			name:         "same_change_both",
			origin:       "line1\nline2\n",
			ours:         "line1a\nline2\n",
			theirs:       "line1a\nline2\n",
			style:        STYLE_DEFAULT,
			wantConflict: false, // Same change should not conflict
		},
		{
			name:         "only_ours_changed",
			origin:       "line1\nline2\n",
			ours:         "line1a\nline2\n",
			theirs:       "line1\nline2\n",
			style:        STYLE_DEFAULT,
			wantConflict: false,
		},
		{
			name:         "only_theirs_changed",
			origin:       "line1\nline2\n",
			ours:         "line1\nline2\n",
			theirs:       "line1b\nline2\n",
			style:        STYLE_DEFAULT,
			wantConflict: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx := context.Background()
			opts := &MergeOptions{
				TextO: tt.origin,
				TextA: tt.ours,
				TextB: tt.theirs,
				Style: tt.style,
				A:     Histogram,
			}

			result, hasConflict, err := MergeParallel(ctx, opts)
			if err != nil {
				t.Fatalf("MergeParallel() error = %v", err)
			}

			if hasConflict != tt.wantConflict {
				t.Errorf("MergeParallel() hasConflict = %v, want %v", hasConflict, tt.wantConflict)
			}

			// Verify conflict markers are present when expected
			if tt.wantConflict && !strings.Contains(result, "<<<<<<<") {
				t.Errorf("MergeParallel() result should contain conflict markers when hasConflict=true")
			}

			if !tt.wantConflict && strings.Contains(result, "<<<<<<<") {
				t.Errorf("MergeParallel() result should not contain conflict markers when hasConflict=false")
			}
		})
	}
}

// ============================================================================
// Comparison Tests: MergeParallel vs Merge
// ============================================================================

// TestMergeParallelVsMerge compares MergeParallel with original Merge
func TestMergeParallelVsMerge(t *testing.T) {
	tests := []struct {
		name   string
		origin string
		ours   string
		theirs string
		style  int
	}{
		{
			name:   "simple_conflict",
			origin: "line1\nline2\n",
			ours:   "line1a\nline2\n",
			theirs: "line1b\nline2\n",
			style:  STYLE_DEFAULT,
		},
		// Note: "adjacent_conflict" test removed because Merge and MergeParallel
		// handle adjacent (non-overlapping) changes differently:
		// - Merge uses <= for overlap check (treats adjacent as conflict)
		// - MergeParallel uses < for overlap check (correct: adjacent is NOT conflict)
		{
			name:   "diff3_style",
			origin: "line1\nline2\n",
			ours:   "line1a\nline2\n",
			theirs: "line1b\nline2\n",
			style:  STYLE_DIFF3,
		},
		{
			name:   "no_trailing_newline_conflict",
			origin: "line1\nline2",
			ours:   "line1\nline2a",
			theirs: "line1\nline2b",
			style:  STYLE_DEFAULT,
		},
		{
			name:   "no_change_ours",
			origin: "line1\nline2\n",
			ours:   "line1\nline2\n",
			theirs: "line1b\nline2\n",
			style:  STYLE_DEFAULT,
		},
		{
			name:   "no_change_theirs",
			origin: "line1\nline2\n",
			ours:   "line1a\nline2\n",
			theirs: "line1\nline2\n",
			style:  STYLE_DEFAULT,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx := context.Background()

			// Original Merge
			optsOriginal := &MergeOptions{
				TextO: tt.origin,
				TextA: tt.ours,
				TextB: tt.theirs,
				Style: tt.style,
				A:     Histogram,
			}
			resultOriginal, conflictOriginal, errOriginal := Merge(ctx, optsOriginal)
			if errOriginal != nil {
				t.Fatalf("Merge() error = %v", errOriginal)
			}

			// MergeParallel
			optsNew := &MergeOptions{
				TextO: tt.origin,
				TextA: tt.ours,
				TextB: tt.theirs,
				Style: tt.style,
				A:     Histogram,
			}
			resultNew, conflictNew, errNew := MergeParallel(ctx, optsNew)
			if errNew != nil {
				t.Fatalf("MergeParallel() error = %v", errNew)
			}

			// Compare conflict flags
			if conflictOriginal != conflictNew {
				t.Errorf("Conflict mismatch: Merge=%v, MergeParallel=%v", conflictOriginal, conflictNew)
			}

			// Compare results
			if resultOriginal != resultNew {
				t.Errorf("Results differ:\nOriginal:\n%s\n\nMergeParallel:\n%s", resultOriginal, resultNew)
			}
		})
	}
}

// ============================================================================
// Label Tests
// ============================================================================

// TestMergeParallelLabels tests label formatting
func TestMergeParallelLabels(t *testing.T) {
	tests := []struct {
		name      string
		labelO    string
		labelA    string
		labelB    string
		wantLabel string
	}{
		{
			name:      "default_labels",
			labelO:    "o.txt",
			labelA:    "a.txt",
			labelB:    "b.txt",
			wantLabel: " a.txt", // ValidateOptions adds space
		},
		{
			name:      "empty_labels",
			labelO:    "",
			labelA:    "",
			labelB:    "",
			wantLabel: "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx := context.Background()
			opts := &MergeOptions{
				TextO:  "line1\nline2\n",
				TextA:  "line1a\nline2\n",
				TextB:  "line1b\nline2\n",
				LabelO: tt.labelO,
				LabelA: tt.labelA,
				LabelB: tt.labelB,
				Style:  STYLE_DEFAULT,
				A:      Histogram,
			}

			result, _, err := MergeParallel(ctx, opts)
			if err != nil {
				t.Fatalf("MergeParallel() error = %v", err)
			}

			if tt.labelA != "" {
				if !strings.Contains(result, tt.wantLabel) {
					t.Errorf("MergeParallel() result should contain label %q, got:\n%s", tt.wantLabel, result)
				}
			}
		})
	}
}

// ============================================================================
// Multi-line Tests
// ============================================================================

// TestMergeParallelMultiLine tests multi-line merges
func TestMergeParallelMultiLine(t *testing.T) {
	tests := []struct {
		name         string
		origin       string
		ours         string
		theirs       string
		wantConflict bool
	}{
		{
			name:         "multi_line_change",
			origin:       "line1\nline2\nline3\nline4\n",
			ours:         "line1\nline2a\nline3\nline4\n",
			theirs:       "line1\nline2\nline3b\nline4\n",
			wantConflict: false, // Adjacent (non-overlapping) modifications should NOT conflict
		},
		{
			name:         "insert_middle",
			origin:       "line1\nline3\n",
			ours:         "line1\nline2\nline3\n",
			theirs:       "line1\nline2\nline3\n",
			wantConflict: false, // Same insert
		},
		{
			name:         "delete_middle",
			origin:       "line1\nline2\nline3\n",
			ours:         "line1\nline3\n",
			theirs:       "line1\nline3\n",
			wantConflict: false, // Same delete
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx := context.Background()
			opts := &MergeOptions{
				TextO: tt.origin,
				TextA: tt.ours,
				TextB: tt.theirs,
				Style: STYLE_DEFAULT,
				A:     Histogram,
			}

			_, hasConflict, err := MergeParallel(ctx, opts)
			if err != nil {
				t.Fatalf("MergeParallel() error = %v", err)
			}

			if hasConflict != tt.wantConflict {
				t.Errorf("MergeParallel() hasConflict = %v, want %v", hasConflict, tt.wantConflict)
			}
		})
	}
}

// ============================================================================
// Context Tests
// ============================================================================

// TestMergeParallelContext tests context cancellation
func TestMergeParallelContext(t *testing.T) {
	ctx, cancel := context.WithCancel(t.Context())
	cancel() // Cancel immediately

	opts := &MergeOptions{
		TextO: "line1\nline2\n",
		TextA: "line1a\nline2\n",
		TextB: "line1b\nline2\n",
		Style: STYLE_DEFAULT,
		A:     Histogram,
	}

	_, _, err := MergeParallel(ctx, opts)
	if err == nil {
		t.Error("MergeParallel() should return error when context is canceled")
	}
}

// ============================================================================
// Options Validation Tests
// ============================================================================

// TestMergeParallelValidateOptions tests option validation
func TestMergeParallelValidateOptions(t *testing.T) {
	tests := []struct {
		name    string
		opts    *MergeOptions
		wantErr bool
	}{
		{
			name:    "nil_options",
			opts:    nil,
			wantErr: true,
		},
		{
			name: "valid_options",
			opts: &MergeOptions{
				TextO: "line1\n",
				TextA: "line1a\n",
				TextB: "line1b\n",
			},
			wantErr: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx := context.Background()
			_, _, err := MergeParallel(ctx, tt.opts)
			if (err != nil) != tt.wantErr {
				t.Errorf("MergeParallel() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

// ============================================================================
// Algorithm Tests
// ============================================================================

// TestMergeParallelAlgorithms tests different diff algorithms
func TestMergeParallelAlgorithms(t *testing.T) {
	algorithms := []Algorithm{
		Histogram,
		Myers,
		ONP,
		Patience,
		Minimal,
	}

	for _, algo := range algorithms {
		t.Run(algo.String(), func(t *testing.T) {
			ctx := context.Background()
			opts := &MergeOptions{
				TextO: "line1\nline2\nline3\n",
				TextA: "line1a\nline2\nline3\n",
				TextB: "line1b\nline2\nline3\n",
				Style: STYLE_DEFAULT,
				A:     algo,
			}

			result, hasConflict, err := MergeParallel(ctx, opts)
			if err != nil {
				t.Fatalf("MergeParallel() with algorithm %s error = %v", algo, err)
			}

			if !hasConflict {
				t.Errorf("MergeParallel() with algorithm %s should detect conflict", algo)
			}

			if !strings.Contains(result, "<<<<<<<") {
				t.Errorf("MergeParallel() result should contain conflict markers")
			}
		})
	}
}

// ============================================================================
// Complex Conflict Tests
// ============================================================================

// TestMergeParallelComplexConflicts tests complex conflict scenarios
func TestMergeParallelComplexConflicts(t *testing.T) {
	tests := []struct {
		name         string
		origin       string
		ours         string
		theirs       string
		wantConflict bool
	}{
		{
			name:         "both_delete_same",
			origin:       "line1\nline2\nline3\n",
			ours:         "line1\nline3\n",
			theirs:       "line1\nline3\n",
			wantConflict: false, // Same delete, no conflict
		},
		{
			name:         "both_delete_different",
			origin:       "line1\nline2\nline3\n",
			ours:         "line1\nline3\n",
			theirs:       "line1\nline2\n",
			wantConflict: false, // Adjacent deletions (line2 vs line3) don't overlap
		},
		{
			name:         "both_insert_same_place",
			origin:       "line1\nline3\n",
			ours:         "line1\nline2\nline3\n",
			theirs:       "line1\nline2a\nline3\n",
			wantConflict: true, // Different insert at same place
		},
		{
			name:         "replace_same_content",
			origin:       "line1\nline2\nline3\n",
			ours:         "line1\nline2a\nline3\n",
			theirs:       "line1\nline2a\nline3\n",
			wantConflict: false, // Same replacement, no conflict
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx := context.Background()
			opts := &MergeOptions{
				TextO: tt.origin,
				TextA: tt.ours,
				TextB: tt.theirs,
				Style: STYLE_DEFAULT,
				A:     Histogram,
			}

			_, hasConflict, err := MergeParallel(ctx, opts)
			if err != nil {
				t.Fatalf("MergeParallel() error = %v", err)
			}

			if hasConflict != tt.wantConflict {
				t.Errorf("MergeParallel() hasConflict = %v, want %v", hasConflict, tt.wantConflict)
			}
		})
	}
}

// ============================================================================
// Empty Region Tests
// ============================================================================

// TestMergeParallelEmptyRegion tests edge cases with empty regions
func TestMergeParallelEmptyRegion(t *testing.T) {
	tests := []struct {
		name         string
		origin       string
		ours         string
		theirs       string
		wantConflict bool
	}{
		{
			name:         "ours_insert_at_beginning",
			origin:       "line1\nline2\n",
			ours:         "line0\nline1\nline2\n",
			theirs:       "line1\nline2\n",
			wantConflict: false,
		},
		{
			name:         "theirs_insert_at_end",
			origin:       "line1\nline2\n",
			ours:         "line1\nline2\n",
			theirs:       "line1\nline2\nline3\n",
			wantConflict: false,
		},
		{
			name:         "both_insert_at_beginning_different",
			origin:       "line1\nline2\n",
			ours:         "line0a\nline1\nline2\n",
			theirs:       "line0b\nline1\nline2\n",
			wantConflict: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx := context.Background()
			opts := &MergeOptions{
				TextO: tt.origin,
				TextA: tt.ours,
				TextB: tt.theirs,
				Style: STYLE_DEFAULT,
				A:     Histogram,
			}

			_, hasConflict, err := MergeParallel(ctx, opts)
			if err != nil {
				t.Fatalf("MergeParallel() error = %v", err)
			}

			if hasConflict != tt.wantConflict {
				t.Errorf("MergeParallel() hasConflict = %v, want %v", hasConflict, tt.wantConflict)
			}
		})
	}
}

// ============================================================================
// Edge Cases Tests
// ============================================================================

// TestMergeParallelEdgeCases tests edge cases for MergeParallel
func TestMergeParallelEdgeCases(t *testing.T) {
	tests := []struct {
		name         string
		origin       string
		ours         string
		theirs       string
		style        int
		wantConflict bool
		description  string
	}{
		// ===== 空值和 null 边界情况 =====
		{
			name:         "all_empty",
			origin:       "",
			ours:         "",
			theirs:       "",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "所有输入为空字符串",
		},
		{
			name:         "only_origin_empty",
			origin:       "",
			ours:         "line1\nline2\n",
			theirs:       "line1\nline2\n",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "只有 origin 为空，ours 和 theirs 相同",
		},
		{
			name:         "origin_empty_ours_theirs_different",
			origin:       "",
			ours:         "line1\n",
			theirs:       "line2\n",
			style:        STYLE_DEFAULT,
			wantConflict: true,
			description:  "origin 为空，ours 和 theirs 不同",
		},
		{
			name:         "single_line_all_empty",
			origin:       "\n",
			ours:         "\n",
			theirs:       "\n",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "所有输入只有一个换行符",
		},

		// ===== 单行边界情况 =====
		{
			name:         "single_line_origin",
			origin:       "line1",
			ours:         "line1",
			theirs:       "line1",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "单行文本，无变化",
		},
		{
			name:         "single_line_modified_ours",
			origin:       "line1",
			ours:         "line1a",
			theirs:       "line1",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "单行文本，只有 ours 修改",
		},
		{
			name:         "single_line_both_modified_same",
			origin:       "line1",
			ours:         "line1a",
			theirs:       "line1a",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "单行文本，ours 和 theirs 修改相同内容",
		},
		{
			name:         "single_line_both_modified_different",
			origin:       "line1",
			ours:         "line1a",
			theirs:       "line1b",
			style:        STYLE_DEFAULT,
			wantConflict: true,
			description:  "单行文本，ours 和 theirs 修改不同内容",
		},
		{
			name:         "single_line_without_newline",
			origin:       "line1",
			ours:         "line1a",
			theirs:       "line1b",
			style:        STYLE_DEFAULT,
			wantConflict: true,
			description:  "单行文本无换行符",
		},

		// ===== 特殊字符和编码 =====
		{
			name:         "unicode_characters",
			origin:       "中文\n日本語\n한국어\n",
			ours:         "中文修改\n日本語\n한국어\n",
			theirs:       "中文\n日本語修改\n한국어\n",
			style:        STYLE_DEFAULT,
			wantConflict: false, // 相邻但不重叠的修改（第一行 vs 第二行）
			description:  "Unicode 多语言字符 - 相邻修改",
		},
		{
			name:         "emoji_characters",
			origin:       "😀\n😎\n",
			ours:         "😊\n😎\n",
			theirs:       "😀\n🥳\n",
			style:        STYLE_DEFAULT,
			wantConflict: false, // 相邻但不重叠的修改（第一行 vs 第二行）
			description:  "Emoji 表情符号 - 相邻修改",
		},
		{
			name:         "special_characters",
			origin:       "line1\ttab\nline2\rcarriage\n",
			ours:         "line1\ttab modified\nline2\rcarriage\n",
			theirs:       "line1\ttab\nline2\rcarriage modified\n",
			style:        STYLE_DEFAULT,
			wantConflict: false, // 相邻但不重叠的修改（第一行 vs 第二行）
			description:  "特殊字符（制表符、回车符）- 相邻修改",
		},
		{
			name:         "mixed_line_endings",
			origin:       "line1\nline2\r\nline3\r",
			ours:         "line1 modified\nline2\r\nline3\r",
			theirs:       "line1\nline2\r\nline3 modified\r",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "混合行结束符（\\n, \\r\\n, \\r）",
		},
		{
			name:         "very_long_line",
			origin:       strings.Repeat("a", 10000) + "\n",
			ours:         strings.Repeat("b", 10000) + "\n",
			theirs:       strings.Repeat("c", 10000) + "\n",
			style:        STYLE_DEFAULT,
			wantConflict: true,
			description:  "超长行（10000 字符）",
		},
		{
			name:         "whitespace_only",
			origin:       "   \n\t\n",
			ours:         "    \n\t\n",
			theirs:       "   \n\t\t\n",
			style:        STYLE_DEFAULT,
			wantConflict: false, // Different lines modified (line1 vs line2), no overlap
			description:  "只有空白字符",
		},
		{
			name:         "null_byte",
			origin:       "line1\x00line2\n",
			ours:         "line1\x00line2 modified\n",
			theirs:       "line1\x00line2\n",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "包含 null 字节（\\x00）",
		},

		// ===== 插入和删除边界情况 =====
		{
			name:         "insert_at_beginning_both",
			origin:       "line1\nline2\n",
			ours:         "inserted\nline1\nline2\n",
			theirs:       "inserted\nline1\nline2\n",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "在开头插入相同内容",
		},
		{
			name:         "insert_at_beginning_different",
			origin:       "line1\nline2\n",
			ours:         "insertedA\nline1\nline2\n",
			theirs:       "insertedB\nline1\nline2\n",
			style:        STYLE_DEFAULT,
			wantConflict: true,
			description:  "在开头插入不同内容",
		},
		{
			name:         "insert_at_end_both",
			origin:       "line1\nline2\n",
			ours:         "line1\nline2\ninserted\n",
			theirs:       "line1\nline2\ninserted\n",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "在末尾插入相同内容",
		},
		{
			name:         "insert_at_end_different",
			origin:       "line1\nline2\n",
			ours:         "line1\nline2\ninsertedA\n",
			theirs:       "line1\nline2\ninsertedB\n",
			style:        STYLE_DEFAULT,
			wantConflict: true,
			description:  "在末尾插入不同内容",
		},
		{
			name:         "delete_all_content",
			origin:       "line1\nline2\nline3\n",
			ours:         "",
			theirs:       "",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "双方都删除所有内容",
		},
		{
			name:         "delete_all_content_ours_only",
			origin:       "line1\nline2\nline3\n",
			ours:         "",
			theirs:       "line1\nline2\nline3\n",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "只有 ours 删除所有内容",
		},
		{
			name:         "delete_middle_lines",
			origin:       "line1\nline2\nline3\nline4\nline5\n",
			ours:         "line1\nline4\nline5\n",
			theirs:       "line1\nline4\nline5\n",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "双方删除相同的中间行",
		},
		{
			name:         "delete_different_lines",
			origin:       "line1\nline2\nline3\nline4\nline5\n",
			ours:         "line1\nline3\nline5\n",
			theirs:       "line1\nline2\nline4\nline5\n",
			style:        STYLE_DEFAULT,
			wantConflict: false, // Adjacent deletions (line2,line4 vs line3), no overlap
			description:  "删除不同的行",
		},
		{
			name:         "insert_multiple_lines",
			origin:       "line1\nline3\n",
			ours:         "line1\nline2a\nline2b\nline3\n",
			theirs:       "line1\nline2a\nline2b\nline3\n",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "双方插入相同的多个行",
		},
		{
			name:         "insert_different_multiple_lines",
			origin:       "line1\nline3\n",
			ours:         "line1\nline2a\nline2b\nline3\n",
			theirs:       "line1\nline2x\nline2y\nline3\n",
			style:        STYLE_DEFAULT,
			wantConflict: true,
			description:  "双方插入不同的多个行",
		},

		// ===== 替换边界情况 =====
		{
			name:         "replace_single_line_same",
			origin:       "line1\nline2\nline3\n",
			ours:         "line1\nmodified\nline3\n",
			theirs:       "line1\nmodified\nline3\n",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "替换同一行相同内容",
		},
		{
			name:         "replace_single_line_different",
			origin:       "line1\nline2\nline3\n",
			ours:         "line1\nmodifiedA\nline3\n",
			theirs:       "line1\nmodifiedB\nline3\n",
			style:        STYLE_DEFAULT,
			wantConflict: true,
			description:  "替换同一行不同内容",
		},
		{
			name:         "replace_multiple_lines_same",
			origin:       "line1\nline2\nline3\nline4\n",
			ours:         "line1\nnew1\nnew2\nline4\n",
			theirs:       "line1\nnew1\nnew2\nline4\n",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "替换多个行相同内容",
		},
		{
			name:         "replace_multiple_lines_different",
			origin:       "line1\nline2\nline3\nline4\n",
			ours:         "line1\nnew1\nnew2\nline4\n",
			theirs:       "line1\nnew3\nnew4\nline4\n",
			style:        STYLE_DEFAULT,
			wantConflict: true,
			description:  "替换多个行不同内容",
		},

		// ===== 复杂冲突场景 =====
		{
			name:         "overlapping_changes",
			origin:       "line1\nline2\nline3\nline4\n",
			ours:         "line1\nmodifiedA\nline3\nline4\n",
			theirs:       "line1\nline2\nmodifiedB\nline4\n",
			style:        STYLE_DEFAULT,
			wantConflict: false, // Adjacent modifications (line2 vs line3), no overlap
			description:  "相邻但不重叠的修改",
		},
		{
			name:         "multiple_conflicts",
			origin:       "line1\nline2\nline3\nline4\nline5\n",
			ours:         "line1a\nline2\nline3a\nline4\nline5\n",
			theirs:       "line1\nline2b\nline3\nline4b\nline5\n",
			style:        STYLE_DEFAULT,
			wantConflict: false, // Adjacent modifications (line1,line3 vs line2,line4), no overlap
			description:  "多个独立的修改，相邻但不重叠",
		},
		{
			name:         "interleaved_changes",
			origin:       "line1\nline2\nline3\nline4\nline5\n",
			ours:         "line1\nline2a\nline3\nline4a\nline5\n",
			theirs:       "line1\nline2b\nline3\nline4b\nline5\n",
			style:        STYLE_DEFAULT,
			wantConflict: true,
			description:  "交替的修改",
		},

		// ===== 冲突样式测试 =====
		{
			name:         "diff3_style_conflict",
			origin:       "line1\nline2\n",
			ours:         "line1a\nline2\n",
			theirs:       "line1b\nline2\n",
			style:        STYLE_DIFF3,
			wantConflict: true,
			description:  "Diff3 样式冲突（包含 origin 内容）",
		},
		{
			name:         "zealous_diff3_style_conflict",
			origin:       "line1\nline2\nline3\n",
			ours:         "line1\nline2a\nline3\n",
			theirs:       "line1\nline2b\nline3\n",
			style:        STYLE_ZEALOUS_DIFF3,
			wantConflict: true,
			description:  "Zealous Diff3 样式冲突",
		},

		// ===== 大文件测试 =====
		{
			name:         "large_file_no_conflict",
			origin:       strings.Repeat("line\n", 100),
			ours:         strings.Repeat("line\n", 50) + "modified\n" + strings.Repeat("line\n", 49),
			theirs:       strings.Repeat("line\n", 100),
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "大文件单行修改无冲突",
		},
		{
			name:         "large_file_with_conflict",
			origin:       strings.Repeat("line\n", 100),
			ours:         strings.Repeat("line\n", 50) + "modifiedA\n" + strings.Repeat("line\n", 49),
			theirs:       strings.Repeat("line\n", 50) + "modifiedB\n" + strings.Repeat("line\n", 49),
			style:        STYLE_DEFAULT,
			wantConflict: true,
			description:  "大文件同位置修改产生冲突",
		},

		// ===== 编码相关测试 =====
		{
			name:         "utf8_bom",
			origin:       "\xef\xbb\xbfline1\nline2\n",
			ours:         "\xef\xbb\xbfline1a\nline2\n",
			theirs:       "\xef\xbb\xbfline1\nline2\n",
			style:        STYLE_DEFAULT,
			wantConflict: false,
			description:  "UTF-8 BOM 处理",
		},
		{
			name:         "different_encodings_treated_as_binary",
			origin:       "line1\nline2\n",
			ours:         "line1a\nline2\n",
			theirs:       "line1b\nline2\n",
			style:        STYLE_DEFAULT,
			wantConflict: true,
			description:  "不同编码处理（作为二进制处理）",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx := context.Background()
			opts := &MergeOptions{
				TextO: tt.origin,
				TextA: tt.ours,
				TextB: tt.theirs,
				Style: tt.style,
				A:     Histogram,
			}

			result, hasConflict, err := MergeParallel(ctx, opts)
			if err != nil {
				t.Fatalf("MergeParallel() error = %v", err)
			}

			if hasConflict != tt.wantConflict {
				t.Errorf("MergeParallel() hasConflict = %v, want %v (%s)", hasConflict, tt.wantConflict, tt.description)
			}

			// Validate result is valid UTF-8
			if !utf8.ValidString(result) {
				t.Errorf("MergeParallel() result is not valid UTF-8")
			}

			// Verify conflict markers are present when expected
			if tt.wantConflict && !strings.Contains(result, "<<<<<<<") {
				t.Errorf("MergeParallel() result should contain conflict markers when hasConflict=true")
			}
		})
	}
}

// ============================================================================
// HasConflictParallel Tests
// ============================================================================

// TestHasConflictParallel tests the HasConflictParallel function
func TestHasConflictParallel(t *testing.T) {
	tests := []struct {
		name      string
		textO     string
		textA     string
		textB     string
		wantTrue  bool
		expectErr bool
	}{
		{
			name:      "no_conflict_only_a_changed",
			textO:     "line1\nline2\nline3\n",
			textA:     "line1a\nline2\nline3\n",
			textB:     "line1\nline2\nline3\n",
			wantTrue:  false,
			expectErr: false,
		},
		{
			name:      "no_conflict_only_b_changed",
			textO:     "line1\nline2\nline3\n",
			textA:     "line1\nline2\nline3\n",
			textB:     "line1\nline2b\nline3\n",
			wantTrue:  false,
			expectErr: false,
		},
		{
			name:      "no_conflict_both_same_change",
			textO:     "line1\nline2\nline3\n",
			textA:     "line1a\nline2\nline3\n",
			textB:     "line1a\nline2\nline3\n",
			wantTrue:  false,
			expectErr: false,
		},
		{
			name:      "conflict_same_line_different_content",
			textO:     "line1\nline2\nline3\n",
			textA:     "line1\nline2a\nline3\n",
			textB:     "line1\nline2b\nline3\n",
			wantTrue:  true,
			expectErr: false,
		},
		{
			name:      "no_conflict_different_lines_adjacent", // 相邻但不重叠的修改（line1 vs line2）
			textO:     "line1\nline2\nline3\n",
			textA:     "line1a\nline2\nline3\n",
			textB:     "line1\nline2b\nline3\n",
			wantTrue:  false, // 相邻但不重叠，不冲突
			expectErr: false,
		},
		{
			name:      "conflict_adjacent_changes",
			textO:     "line1\nline2\nline3\n",
			textA:     "line1a\nline2\nline3\n",
			textB:     "line1b\nline2\nline3\n",
			wantTrue:  true,
			expectErr: false,
		},
		{
			name:      "no_conflict_all_same",
			textO:     "line1\nline2\nline3\n",
			textA:     "line1\nline2\nline3\n",
			textB:     "line1\nline2\nline3\n",
			wantTrue:  false,
			expectErr: false,
		},
		{
			name:      "no_conflict_empty_texts",
			textO:     "",
			textA:     "",
			textB:     "",
			wantTrue:  false,
			expectErr: false,
		},
		{
			name:      "conflict_empty_origin",
			textO:     "",
			textA:     "line1\n",
			textB:     "line2\n",
			wantTrue:  true,
			expectErr: false,
		},
		{
			name:      "conflict_insert_at_same_position_different_content",
			textO:     "line1\nline3\n",
			textA:     "line1\nline2a\nline3\n",
			textB:     "line1\nline2b\nline3\n",
			wantTrue:  true,
			expectErr: false,
		},
		{
			name:      "conflict_insert_at_same_position",
			textO:     "line1\nline3\n",
			textA:     "line1\nline2a\nline3\n",
			textB:     "line1\nline2b\nline3\n",
			wantTrue:  true,
			expectErr: false,
		},
		{
			name:      "no_conflict_delete_same_line",
			textO:     "line1\nline2\nline3\n",
			textA:     "line1\nline3\n",
			textB:     "line1\nline3\n",
			wantTrue:  false,
			expectErr: false,
		},
		{
			name:      "conflict_delete_different_lines",
			textO:     "line1\nline2\nline3\n",
			textA:     "line1\nline3\n",
			textB:     "line1\nline2\n",
			wantTrue:  false, // Adjacent deletions (line2 vs line3), no overlap
			expectErr: false,
		},
		{
			name:      "no_conflict_single_line",
			textO:     "line1\n",
			textA:     "line1\n",
			textB:     "line1\n",
			wantTrue:  false,
			expectErr: false,
		},
		{
			name:      "conflict_single_line",
			textO:     "line1\n",
			textA:     "line1a\n",
			textB:     "line1b\n",
			wantTrue:  true,
			expectErr: false,
		},
		{
			name:      "no_conflict_multiple_changes_separated",
			textO:     "line1\nline2\nline3\nline4\nline5\n",
			textA:     "line1a\nline2\nline3\nline4\nline5\n",
			textB:     "line1\nline2\nline3\nline4b\nline5\n",
			wantTrue:  false,
			expectErr: false,
		},
		{
			name:      "conflict_multiple_overlapping_changes",
			textO:     "line1\nline2\nline3\nline4\nline5\n",
			textA:     "line1\nline2a\nline3a\nline4\nline5\n",
			textB:     "line1\nline2b\nline3b\nline4\nline5\n",
			wantTrue:  true,
			expectErr: false,
		},
	}

	ctx := context.Background()

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := HasConflictParallel(ctx, tt.textO, tt.textA, tt.textB)

			if (err != nil) != tt.expectErr {
				t.Errorf("HasConflictParallel() error = %v, expectErr %v", err, tt.expectErr)
				return
			}

			if got != tt.wantTrue {
				t.Errorf("HasConflictParallel() = %v, want %v", got, tt.wantTrue)
			}
		})
	}
}

// TestHasConflictParallelVsMerge tests that HasConflictParallel is consistent with MergeParallel
func TestHasConflictParallelVsMerge(t *testing.T) {
	tests := []struct {
		name  string
		textO string
		textA string
		textB string
	}{
		{
			name:  "simple_conflict",
			textO: "line1\nline2\nline3\n",
			textA: "line1\nline2a\nline3\n",
			textB: "line1\nline2b\nline3\n",
		},
		{
			name:  "no_conflict",
			textO: "line1\nline2\nline3\n",
			textA: "line1\nline2a\nline3\n",
			textB: "line1\nline2\nline3\n",
		},
		{
			name:  "adjacent_changes",
			textO: "line1\nline2\nline3\n",
			textA: "line1a\nline2\nline3\n",
			textB: "line1b\nline2\nline3\n",
		},
		{
			name:  "same_change",
			textO: "line1\nline2\nline3\n",
			textA: "line1\nline2a\nline3\n",
			textB: "line1\nline2a\nline3\n",
		},
	}

	ctx := context.Background()

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Check with HasConflictParallel
			hasConflict, err := HasConflictParallel(ctx, tt.textO, tt.textA, tt.textB)
			if err != nil {
				t.Fatalf("HasConflictParallel() error = %v", err)
			}

			// Check with MergeParallel
			opts := &MergeOptions{
				TextO: tt.textO,
				TextA: tt.textA,
				TextB: tt.textB,
				Style: STYLE_DEFAULT,
				A:     Histogram,
			}
			_, mergeHasConflict, err := MergeParallel(ctx, opts)
			if err != nil {
				t.Fatalf("MergeParallel() error = %v", err)
			}

			// They should match
			if hasConflict != mergeHasConflict {
				t.Errorf("HasConflictParallel() = %v, MergeParallel() = %v, should match",
					hasConflict, mergeHasConflict)
			}
		})
	}
}

// TestHasConflictParallelContextCancellation tests context cancellation
func TestHasConflictParallelContextCancellation(t *testing.T) {
	tests := []struct {
		name         string
		cancelBefore bool
		cancelDuring bool
		expectError  bool
	}{
		{
			name:         "cancel_before_merge",
			cancelBefore: true,
			expectError:  true,
		},
		{
			name:         "no_cancellation",
			cancelBefore: false,
			expectError:  false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancel := context.WithCancel(t.Context())

			if tt.cancelBefore {
				cancel()
			}

			textO := "line1\nline2\nline3\n"
			textA := "line1\nline2a\nline3\n"
			textB := "line1\nline2\nline3\n"

			_, err := HasConflictParallel(ctx, textO, textA, textB)

			if tt.expectError && err == nil {
				t.Error("expected error but got nil")
			}

			if !tt.expectError && err != nil {
				t.Errorf("unexpected error: %v", err)
			}

			cancel()
		})
	}
}
