// Code generated by running "go generate". DO NOT EDIT.
// See gen_unicode.go for generation logic.

package diferenco

//go:generate go run gen_unicode.go

// interval represents a Unicode code point range [First, Last].
type interval struct {
	First rune
	Last  rune
}

// isCJK returns true if r is a CJK (East Asian Wide/Fullwidth) character.
func isCJK(r rune) bool {
	return inRange(cjkRanges, r)
}

// isEmoji returns true if r is an emoji character.
func isEmoji(r rune) bool {
	return inRange(emojiRanges, r)
}

// inRange performs binary search to check if r is within any interval in ranges.
func inRange(ranges []interval, r rune) bool {
	n := len(ranges)
	i, j := 0, n
	for i < j {
		h := i + (j-i)/2
		if r < ranges[h].First {
			j = h
			continue
		}
		if r > ranges[h].Last {
			i = h + 1
			continue
		}
		return true
	}
	return false
}
